POST http://localHost:8080/auth/register HTTP/1.1
content-type: application/json

{
    "username": "admina",
    "password": "asda"
}

###

POST http://localHost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admina",
    "password": "asda"
}

###

GET http://localHost:8080/message/userList HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluYSIsImlhdCI6MTYzOTIzMzc4MiwiZXhwIjoxNjM5MjMzNzkyfQ.o9rAMv_DXCg-g-P8KI5Db7EESDthDiAhGA7jxa_SxfI

###

POST http://localHost:8080/auth/token HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluYSIsImlhdCI6MTYzOTIzNTA4OCwiZXhwIjoxNjM5MjM4Njg4fQ.5CfQUQgKCUd-F68Tjr-pmc7vQLkejoFkqMVQi_cF1so"
}